---
- name: Get volume information
  hosts: localhost
  gather_facts: false
  vars_files:
    vars.yml
  vars:
    credfile: "~/Documents/.mycreds/democreds.yml"
  tasks:

### Get the credentials from either a local file or an Ansible Tower Custom Credential
  - name: Check for credentials file
    stat:
      path: "{{ credfile }}"
    register: stat_results

  - name: Define credentials using local file
    block:

    - name: Include variable definitions from local file
      include_vars:
        file: "{{ credfile }}"

    - name: Define Ansible Tower credentials based on local file
      set_fact:
        ontap_username: "{{ cf_ontap_username }}"
        ontap_password: "{{ cf_ontap_password }}"

    when: stat_results.stat.exists

  - name: Define credentials using Ansible Tower custom credentials
    block:

    - name: Define Ansible Tower credentials based on custom credential
      set_fact:
        ontap_username: "{{ at_ontap_username }}"
        ontap_password: "{{ at_ontap_password }}"

    when: not stat_results.stat.exists
### End get the credentials from either a local file or an Ansible Tower Custom Credential

  - name: Define connection variable
    set_fact:
      ontap_connection: &ontap_connection_info
        hostname: "{{ ontap_hostname }}"
        username: "{{ ontap_username }}"
        password: "{{ ontap_password }}"
        https: true
        validate_certs: false

  - name: Get list of volumes
    na_ontap_command:
      command: ['volume', 'show']
      <<: *ontap_connection_info
    register: vol_info

  - name: Print volume info
    debug:
      var: vol_info
